<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.ash.messaging</groupId>
    <artifactId>pravaha</artifactId>
    <version>1.0.0</version>
  </parent>
  <artifactId>pravaha-serving</artifactId>
  <name>Pravaha :: serving</name>
  <dependencies>
    <dependency>
      <groupId>com.ash.messaging</groupId>
      <artifactId>pravaha-api</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.ash.messaging</groupId>
      <artifactId>pravaha-common</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.ash.messaging</groupId>
      <artifactId>pravaha-state</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.ash.messaging</groupId>
      <artifactId>pravaha-security</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.ash.messaging</groupId>
      <artifactId>pravaha-sql</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.ash.messaging</groupId>
      <artifactId>pravaha-runtime</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>net.jqwik</groupId>
      <artifactId>jqwik</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
