# Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>. All rights reserved.
# Proprietary and confidential; see LICENSE at the repository root.
"""
The deck, checked by the same tool that claims to check it.

``tools/deck/GUIDE.md`` makes the geometry audit the shipping gate for the deck.
A gate wired into no test is a gate somebody forgets, so the deck in ``docs/`` is
audited here, its slide count is asserted (a deck module that silently lost
slides still builds), every slide is checked to name its source in its speaker
notes, and the document properties are checked to name the author and nothing
else.

    tools/deck/.venv/bin/python -m pytest -q tests/deck

Project Pravaha -- Ask once. Answer always.
Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>. All rights reserved.
PROPRIETARY AND CONFIDENTIAL. See LICENSE at the repository root.
"""

from __future__ import annotations

import pathlib
import subprocess
import sys

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[2]
AUDIT = ROOT / "tools" / "deck" / "audit.py"
DECK = ROOT / "docs" / "Pravaha-Continuous-SQL-Engine-Design-and-Evidence.pptx"
SLIDES = 91

# Anywhere in the file: no tool or assistant credited as a maker of the deck.
FORBIDDEN = (
    "python-pptx",
    "generated by",
    "generated using",
    "generated with",
    "co-authored",
    "anthropic",
)
# In the document properties, which describe the file itself, stricter still.
FORBIDDEN_IN_PROPERTIES = FORBIDDEN + ("generated", "claude")


def _deck():
    pptx = pytest.importorskip("pptx")
    return pptx.Presentation(str(DECK))


def test_the_deck_has_no_geometry_issues():
    pytest.importorskip("pptx")
    result = subprocess.run(
        [sys.executable, str(AUDIT), str(DECK)], capture_output=True, text=True, cwd=ROOT
    )
    assert "no geometry issues detected" in result.stdout, (
        f"{DECK.name}:\n{result.stdout}{result.stderr}\n"
        "Rebuild with tools/deck/build.py and fix the slide the report names."
    )


def test_the_deck_has_the_slides_the_guide_claims():
    assert len(_deck().slides) == SLIDES


def test_every_slide_names_its_source():
    missing = []
    for i, slide in enumerate(_deck().slides, 1):
        notes = slide.notes_slide.notes_text_frame.text if slide.has_notes_slide else ""
        if not notes.startswith("Source:"):
            missing.append(i)
    assert not missing, f"slides without a 'Source:' note: {missing}"


def test_the_deck_names_its_author_and_no_tool():
    prs = _deck()
    props = prs.core_properties
    assert props.author == "Ashutosh Sinha" and props.last_modified_by == "Ashutosh Sinha"
    assert props.title and props.subject
    fields = [props.title, props.subject, props.comments, props.keywords, props.category]
    text = " ".join(f or "" for f in fields)
    assert not [w for w in FORBIDDEN_IN_PROPERTIES if w in text.lower()]
    for slide in prs.slides:
        for shape in slide.shapes:
            if shape.has_text_frame:
                text += " " + shape.text_frame.text
            if getattr(shape, "has_table", False):
                text += " " + " ".join(c.text for r in shape.table.rows for c in r.cells)
    lowered = text.lower()
    assert not [w for w in FORBIDDEN if w in lowered]


def test_the_audit_can_see_tables_at_all():
    """A guard on the gate: an audit that skipped graphic frames would pass a deck
    full of collisions."""
    source = AUDIT.read_text(encoding="utf-8")
    assert "has_table" in source
    assert "table_height" in source
    assert "is_opaque" in source
