"""Builds the assistant's worked examples and its golden set from examples/case-studies.

Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>. All rights reserved.
PROPRIETARY AND CONFIDENTIAL. See the LICENSE file for the full terms.

Two package resources, both generated, never edited (ADR-058 §2 and §4):

* ``pravaha/assist/resources/examples.json`` -- every continuous query of every case study, as
  a description (the README's heading for it and the paragraph that explains it), its reference
  SQL (``sql/NN-continuous-*.sql``), its key (``schema/views.properties``) and the streams it
  reads (``schema/streams.properties``). ``pravaha ask`` gives the model the two to four most
  similar to the request.
* ``pravaha/assist/resources/golden-set.json`` -- the evaluation's cases: one per example
  (description -> reference SQL and key), plus the negative cases below, which must be refused
  or must raise a question.

A test fails when a case study changes and these were not rebuilt
(``tests/test_assist_drafting.py``)::

    cd sdk/python
    .venv/bin/python tools/build_examples.py           # rewrite both resources
    .venv/bin/python tools/build_examples.py --check   # exit 1 if either is stale

Standard library only; deterministic (sorted, no timestamps), so unchanged studies rebuild
byte-identical files.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import sys
from typing import Any, Optional

HERE = pathlib.Path(__file__).resolve().parent
SDK = HERE.parent
SOURCE = SDK.parent.parent / "examples" / "case-studies"
RESOURCES = SDK / "pravaha" / "assist" / "resources"
EXAMPLES = RESOURCES / "examples.json"
GOLDEN = RESOURCES / "golden-set.json"
SOURCE_NAME = "examples/case-studies"
HEADER = ("Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>. All rights reserved. "
          "PROPRIETARY AND CONFIDENTIAL. Generated by sdk/python/tools/build_examples.py from "
          "examples/case-studies; never edit it by hand.")
#: A description is the heading and at most this much of the paragraph under the SQL.
DESCRIPTION_LIMIT = 420

_LINK = re.compile(r"\(sql/(?P<file>[0-9]{2}-continuous-[a-z0-9-]+\.sql)\)")
_HEADING = re.compile(r"^(#{1,6})\s+(.+?)\s*$")
_STEP = re.compile(r"^Step\s+\w+\s+[—-]\s+", re.IGNORECASE)
_WORD = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")

#: Descriptions that must NOT produce an accepted query: the engine refuses what they ask for, or
#: the faithful answer is a question. Each needs only streams of the case studies (``requires``),
#: so it runs on the same engine as the reference cases; ``absent`` names what must not exist.
NEGATIVES: "list[dict[str, Any]]" = [
    {
        "id": "negative/unbounded-group-by",
        "study": "banking-card-velocity",
        "description": "For every card, the total number of approved authorisations it has ever "
                       "had, since the card was first seen, kept forever -- not per minute, not "
                       "per hour, no time window at all.",
        "streams": ["card_auth"],
        "requires": ["card_auth"],
        "expect": ["refused", "questions"],
        "why": "An unwindowed GROUP BY over a stream keeps one entry per card forever; the engine "
               "refuses it (PRV-2050). Adding a window answers a different question.",
    },
    {
        "id": "negative/join-without-time-bound",
        "study": "adtech-click-attribution",
        "description": "Match every click to the impression it claims to follow, however long "
                       "after the impression the click came -- hours, days or months later, with "
                       "no attribution window.",
        "streams": ["ad_click", "ad_impression"],
        "requires": ["ad_click", "ad_impression"],
        "expect": ["refused", "questions"],
        "why": "A join between two streams keeps state only for a bounded time: an unbounded "
               "match is not something the engine keeps (§7, §14), and a time bound changes what "
               "was asked. The faithful answer is a question.",
    },
    {
        "id": "negative/stream-does-not-exist",
        "study": "lakehouse-orders-iceberg",
        "description": "Refunds per region per hour, from the refunds stream.",
        "streams": ["refunds"],
        "requires": ["order_line"],
        "absent": ["refunds"],
        "expect": ["refused", "questions"],
        "why": "There is no refunds stream. Answering from another stream answers a different "
               "question; the model must ask, or name the stream and be refused.",
    },
]


def _properties(path: pathlib.Path) -> "dict[str, str]":
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def _fields(text: str) -> "list[dict[str, Any]]":
    fields = []
    for part in text.split(","):
        if ":" not in part:
            continue
        name, kind = (p.strip() for p in part.split(":", 1))
        nullable = kind.endswith("?")
        fields.append({"name": name, "type": kind.rstrip("?"), "nullable": nullable})
    return fields


def streams_of(study: pathlib.Path) -> "list[dict[str, Any]]":
    props = _properties(study / "schema" / "streams.properties")
    names = sorted({key.split(".")[1] for key in props if key.startswith("stream.")})
    out = []
    for name in names:
        prefix = f"stream.{name}."
        out.append({
            "name": name,
            "role": props.get(prefix + "role", "source"),
            "fields": _fields(props.get(prefix + "fields", "")),
            "eventTime": props.get(prefix + "event-time"),
            "outOfOrderness": props.get(prefix + "out-of-orderness"),
        })
    return out


def _clean(text: str) -> str:
    text = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", text)      # links to their words
    text = re.sub(r"\*\*|__", "", text)
    return re.sub(r"\s+", " ", text).strip()


def _paragraphs(lines: "list[str]") -> "list[str]":
    """Prose paragraphs, skipping code fences, headings, tables, lists and quotes."""
    out: list[str] = []
    current: list[str] = []
    fenced = False
    in_list = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("```") or stripped.startswith("~~~"):
            fenced = not fenced
            if current:
                out.append(" ".join(current))
                current = []
            continue
        if fenced:
            continue
        starts_list = bool(re.match(r"^([-*+]|\d+\.)\s", stripped))
        if starts_list:
            in_list = True
        elif not stripped:
            in_list = False
        continuing = in_list and line[:1].isspace()
        if not stripped or stripped[0] in "#|>" or starts_list or continuing:
            if current:
                out.append(" ".join(current))
                current = []
            continue
        current.append(stripped)
    if current:
        out.append(" ".join(current))
    return out


def _without_lead_in(paragraph: str) -> str:
    """A paragraph without its last sentence when that one introduces a list or a block."""
    sentences = re.split(r"(?<=[.!?:])\s+", paragraph.strip())
    while sentences and sentences[-1].endswith(":"):
        sentences.pop()
    return " ".join(sentences)


def _cut(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    sentences = re.split(r"(?<=[.!?])\s+", text)
    kept = ""
    for sentence in sentences:
        if kept and len(kept) + 1 + len(sentence) > limit:
            break
        kept = f"{kept} {sentence}".strip()
    return kept if kept else text[:limit].rstrip() + "…"


def describe(readme: str, file: str, title: str) -> "tuple[str, str]":
    """``(heading, description)`` for the query in ``sql/<file>``, from the README."""
    lines = readme.splitlines()
    at = next((i for i, line in enumerate(lines) if f"(sql/{file})" in line), None)
    heading = ""
    if at is not None:
        for j in range(at, -1, -1):
            match = _HEADING.match(lines[j])
            if match and len(match.group(1)) >= 2:
                words = re.sub(r",?\s*\[`?sql/[^\]]*\]\([^)]*\)", "", match.group(2))
                heading = _clean(words.strip("`").rstrip(" ,:"))
                break
        end = next((k for k in range(at + 1, len(lines)) if _HEADING.match(lines[k])), len(lines))
        prose = [p for p in (_without_lead_in(p) for p in _paragraphs(lines[at + 1:end])
                             if "(sql/" not in p) if p]
    else:
        prose = []
    heading = _STEP.sub("", heading)
    generic = not heading or re.search(r"\bthe (continuous )?quer(y|ies)\b", heading, re.I)
    if generic:
        heading = title
        problem = _section_prose(readme, "The problem")
        prose = problem[:1] + prose
    body = _cut(_clean(prose[0]), DESCRIPTION_LIMIT) if prose else ""
    heading = heading[0].upper() + heading[1:] if heading else heading
    text = f"{heading}. {body}".strip() if body else f"{heading} ({title})"
    return heading, text


def _section_prose(readme: str, name: str) -> "list[str]":
    lines = readme.splitlines()
    start = next((i for i, line in enumerate(lines)
                  if _HEADING.match(line) and _HEADING.match(line).group(2).strip() == name), None)  # type: ignore[union-attr]
    if start is None:
        return []
    end = next((k for k in range(start + 1, len(lines)) if _HEADING.match(lines[k])), len(lines))
    return _paragraphs(lines[start + 1:end])


def _title(readme: str) -> str:
    for line in readme.splitlines():
        match = _HEADING.match(line)
        if match and len(match.group(1)) == 1:
            return _clean(match.group(2).split(" — ")[0])
    return ""


_CREATE = re.compile(r"^\s*CREATE\s+(OR\s+REPLACE\s+)?CONTINUOUS\s+QUERY\b", re.IGNORECASE)
_BODY = re.compile(r"^\s*AS\s*$|\bAS\s+(?=SELECT\b)", re.IGNORECASE | re.MULTILINE)


def split_statement(sql: str) -> "tuple[str, dict[str, Optional[str]]]":
    """A ``CREATE CONTINUOUS QUERY`` file as its ``SELECT`` and the options it declares (the
    assistant drafts the ``SELECT`` and the options separately); a bare ``SELECT`` unchanged."""
    options: dict[str, Optional[str]] = {"index": None, "lane": None, "retention": None,
                                         "sink": None}
    if not _CREATE.match(sql):
        return sql, options
    match = _BODY.search(sql)
    if match is None:
        return sql, options
    head, body = sql[:match.start()], sql[match.end():].strip()
    index = re.search(r"\bINDEX\s*\(\s*(\w+)\s*\)", head, re.IGNORECASE)
    retain = re.search(r"\bRETAIN\s+(FOR\s+(\S+)|FOREVER)", head, re.IGNORECASE)
    sink = re.search(r"\bWRITING\s+TO\s+(\w+)", head, re.IGNORECASE)
    options["index"] = index.group(1) if index else None
    if retain:
        options["retention"] = retain.group(2).strip("'") if retain.group(2) else "forever"
    options["sink"] = sink.group(1) if sink else None
    return body, options


def reads(sql: str, names: "list[str]") -> "list[str]":
    words = {w.lower() for w in _WORD.findall(re.sub(r"'[^']*'", "", sql))}
    return sorted(n for n in names if n.lower() in words)


def collect(source: pathlib.Path) -> "tuple[dict[str, Any], list[dict[str, Any]], str]":
    studies: dict[str, Any] = {}
    examples: list[dict[str, Any]] = []
    digest = hashlib.sha256()
    for study in sorted(p for p in source.iterdir() if p.is_dir()):
        readme_path = study / "README.md"
        views = _properties(study / "schema" / "views.properties")
        if not readme_path.exists() or not views:
            continue
        readme = readme_path.read_text(encoding="utf-8")
        for part in (readme_path, study / "schema" / "views.properties",
                     study / "schema" / "streams.properties"):
            if part.exists():
                digest.update(part.relative_to(source).as_posix().encode())
                digest.update(part.read_bytes())
        title = _title(readme)
        streams = streams_of(study)
        studies[study.name] = {"title": title, "streams": streams}
        names = [s["name"] for s in streams]
        for key in sorted(k for k in views if k.count(".") == 1):
            view = key.split(".", 1)[1]
            file = views[key]
            sql_path = study / "sql" / file
            sql = sql_path.read_text(encoding="utf-8").strip()
            digest.update(sql_path.relative_to(source).as_posix().encode())
            digest.update(sql.encode())
            heading, description = describe(readme, file, title)
            keys = [k.strip() for k in views.get(f"{key}.keys", "").split(",") if k.strip()]
            sql, options = split_statement(sql)
            examples.append({
                "id": f"{study.name}/{view}",
                "study": study.name,
                "view": view,
                "file": f"{SOURCE_NAME}/{study.name}/sql/{file}",
                "title": heading,
                "description": description,
                "sql": sql,
                "keys": keys,
                "options": options,
                "streams": reads(sql, names),
            })
    return studies, examples, digest.hexdigest()


def render(source: pathlib.Path) -> "tuple[str, str]":
    """``(examples.json, golden-set.json)`` as text."""
    studies, examples, sha = collect(source)
    example_doc = {
        "$comment": HEADER,
        "source": SOURCE_NAME,
        "sourceSha256": sha,
        "studies": studies,
        "examples": examples,
    }
    cases: list[dict[str, Any]] = []
    for example in examples:
        cases.append({
            "id": example["id"],
            "kind": "reference",
            "study": example["study"],
            "description": example["description"],
            "streams": example["streams"],
            "requires": example["streams"],
            "reference": {"name": example["view"], "sql": example["sql"], "keys": example["keys"],
                          "options": example["options"]},
            "expect": ["accepted"],
        })
    for negative in NEGATIVES:
        cases.append({**negative, "kind": "negative"})
    golden_doc = {
        "$comment": HEADER,
        "source": SOURCE_NAME,
        "sourceSha256": sha,
        "cases": cases,
    }
    dump = lambda doc: json.dumps(doc, indent=1, sort_keys=True, ensure_ascii=False) + "\n"  # noqa: E731
    return dump(example_doc), dump(golden_doc)


def main(argv: "Optional[list[str]]" = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if a resource is stale")
    parser.add_argument("--source", type=pathlib.Path, default=SOURCE)
    parser.add_argument("--out", type=pathlib.Path, default=RESOURCES)
    args = parser.parse_args(argv)
    fresh = dict(zip(("examples.json", "golden-set.json"), render(args.source)))
    if args.check:
        stale = [name for name, text in fresh.items()
                 if not (args.out / name).exists()
                 or (args.out / name).read_text(encoding="utf-8") != text]
        if stale:
            print(f"stale: {', '.join(stale)}: run tools/build_examples.py", file=sys.stderr)
            return 1
        return 0
    args.out.mkdir(parents=True, exist_ok=True)
    for name, text in fresh.items():
        (args.out / name).write_text(text, encoding="utf-8")
        print(f"wrote {args.out / name} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
