/*
 * Project Pravaha -- Ask once. Answer always.
 *
 * Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
 * All rights reserved.
 *
 * PROPRIETARY AND CONFIDENTIAL.
 *
 * This file is the confidential and proprietary property of Ashutosh Sinha.
 * Unauthorised copying, use, modification, distribution or disclosure of this
 * file, via any medium, is strictly prohibited except with the express prior
 * written permission of the copyright holder.
 *
 * See the LICENSE file in the root of this repository for the full terms.
 */
package com.ash.messaging.pravaha.codegen;

import java.util.ArrayList;
import java.util.List;

import com.ash.messaging.pravaha.api.PravahaException;
import com.ash.messaging.pravaha.api.data.StreamSchema;
import com.ash.messaging.pravaha.api.data.TypeName;
import com.ash.messaging.pravaha.common.row.RowLayout;
import com.ash.messaging.pravaha.runtime.plan.FilterOperator;
import com.ash.messaging.pravaha.runtime.plan.PhysicalOperator;
import com.ash.messaging.pravaha.runtime.plan.ProjectOperator;
import com.ash.messaging.pravaha.runtime.plan.ScanOperator;

/**
 * Generates one fused method for a chain of filters and projections.
 *
 * <p>Fusion is the whole point. An interpreted chain pays, per record per operator, a megamorphic
 * virtual call, a boxed round trip, and an ordinal lookup. Fused code pays none of them: the filter's
 * test and the projection's field copies become straight-line code in a single counted loop the JIT
 * can unroll and vectorise. That is the difference between roughly 100 k and roughly 1 M records per
 * second per core (design section 12.1), and it is why the 1.0 draft's `Enumerable` execution model could
 * not have met its own targets.
 *
 * <p>Scope in this wave is filter and project. Aggregates end a stage because they buffer state, and
 * joins because they are an exchange point (design section 12.2). Anything outside that scope raises
 * {@code PRV-3101} and the caller uses the interpreted path -- which is the guarantee that
 * correctness never depends on generation succeeding.
 */
public final class FilterProjectGenerator {

    /** A fused chain and the shape it emits. */
    public record Fused(String source, String className, StreamSchema inputSchema, StreamSchema outputSchema) {}

    /**
     * Generates a fused stage.
     *
     * @param plan a chain of filters and projections rooted at a scan
     * @throws PravahaException {@code PRV-3101} if the chain contains anything not yet generable
     */
    public Fused generate(PhysicalOperator plan, String className) {
        List<PhysicalOperator> chain = flatten(plan);
        ScanOperator scan = (ScanOperator) chain.get(chain.size() - 1);
        StreamSchema inputSchema = scan.outputSchema();
        StreamSchema outputSchema = plan.outputSchema();

        RowLayout inputLayout = RowLayout.of(inputSchema);
        RowLayout outputLayout = RowLayout.of(outputSchema);
        PredicateSource predicates = new PredicateSource(inputSchema);

        // Filters are emitted innermost-first so the cheapest rejection happens earliest; the
        // ordering Calcite chose is preserved rather than second-guessed.
        List<String> tests = new ArrayList<>();
        List<Integer> projection = identity(inputSchema.fieldCount());
        for (int i = chain.size() - 2; i >= 0; i--) {
            PhysicalOperator operator = chain.get(i);
            if (operator instanceof FilterOperator filter) {
                tests.add(predicates.emit("row", filter.predicate()));
            } else if (operator instanceof ProjectOperator project) {
                projection = project.sourceOrdinals();
            }
        }

        SourceBuilder source = new SourceBuilder();
        emitClass(source, className, predicates, tests, projection, inputLayout, outputLayout, outputSchema);
        return new Fused(source.toString(), className, inputSchema, outputSchema);
    }

    private void emitClass(
            SourceBuilder source,
            String className,
            PredicateSource predicates,
            List<String> tests,
            List<Integer> projection,
            RowLayout inputLayout,
            RowLayout outputLayout,
            StreamSchema outputSchema) {

        source.comment("GENERATED by Pravaha. Do not edit; regenerate from the plan.")
                .comment("Fused stage: " + tests.size() + " filter(s) then a " + projection.size()
                        + "-column projection.")
                .blank()
                .open("public final class " + className + " implements com.ash.messaging.pravaha.codegen.FusedStage {");

        predicates.emitLiteralFields(source);
        source.blank();

        source.comment("Field offsets are compile-time constants: a read is one load, not a lookup.")
                .open("public int process(com.ash.messaging.pravaha.common.memory.MemoryRegion region,"
                        + " long[] rowOffsets, int count,"
                        + " com.ash.messaging.pravaha.common.memory.MemoryRegion out,"
                        + " long[] outOffsets, int outBase) {")
                .line("int emitted = 0;")
                .open("for (int i = 0; i < count; i++) {")
                .line("int row = (int) rowOffsets[i];");

        for (String test : tests) {
            source.comment("WHERE " + test.replace("\n", " "))
                    .open("if (!" + test + ") {")
                    .line("continue;")
                    .close();
        }

        source.comment("Projection: copy the selected columns into the output row.")
                .line("int outRow = (int) outOffsets[outBase + emitted];")
                .comment("Clear the header and null bitmap; arena space is reused between batches.")
                .line("out.setMemory(outRow, " + outputLayout.fixedEnd() + ", (byte) 0);");

        emitProjection(source, projection, inputLayout, outputLayout, outputSchema);

        source.comment("Header: the Z-set weight travels with the row (design 9.2).")
                .line("out.putLong(outRow + " + RowLayout.OFFSET_WEIGHT + ", region.getLong(row + "
                        + RowLayout.OFFSET_WEIGHT + "));")
                .line("out.putLong(outRow + " + RowLayout.OFFSET_EVENT_TIME + ", region.getLong(row + "
                        + RowLayout.OFFSET_EVENT_TIME + "));")
                .line("out.putLong(outRow + " + RowLayout.OFFSET_SEQUENCE + ", region.getLong(row + "
                        + RowLayout.OFFSET_SEQUENCE + "));")
                .line("out.putInt(outRow + " + RowLayout.OFFSET_TOTAL_LENGTH + ", " + outputLayout.fixedEnd() + ");")
                .line("emitted++;")
                .close()
                .line("return emitted;")
                .close()
                .close();
    }

    private void emitProjection(
            SourceBuilder source,
            List<Integer> projection,
            RowLayout inputLayout,
            RowLayout outputLayout,
            StreamSchema outputSchema) {

        for (int out = 0; out < projection.size(); out++) {
            int in = projection.get(out);
            int from = inputLayout.offsetOf(in);
            int to = outputLayout.offsetOf(out);
            TypeName type = outputSchema.field(out).type().typeName();

            switch (type) {
                case BOOLEAN ->
                    source.line("out.putBoolean(outRow + " + to + ", region.getBoolean(row + " + from + "));");
                case INT8 -> source.line("out.putByte(outRow + " + to + ", region.getByte(row + " + from + "));");
                case INT16 -> source.line("out.putShort(outRow + " + to + ", region.getShort(row + " + from + "));");
                case INT32, DATE -> source.line("out.putInt(outRow + " + to + ", region.getInt(row + " + from + "));");
                case INT64, TIME, TIMESTAMP_LTZ ->
                    source.line("out.putLong(outRow + " + to + ", region.getLong(row + " + from + "));");
                case FLOAT32 -> source.line("out.putFloat(outRow + " + to + ", region.getFloat(row + " + from + "));");
                case FLOAT64 ->
                    source.line("out.putDouble(outRow + " + to + ", region.getDouble(row + " + from + "));");
                default ->
                    throw new PravahaException(
                            CodegenErrors.UNSUPPORTED,
                            "cannot generate a projection of " + type + " yet (column '"
                                    + outputSchema.field(out).name()
                                    + "'). The interpreted path handles it; this stage falls back.");
            }
        }
    }

    /** Flattens a linear chain, root first, scan last. */
    private static List<PhysicalOperator> flatten(PhysicalOperator plan) {
        List<PhysicalOperator> chain = new ArrayList<>();
        PhysicalOperator current = plan;
        while (true) {
            chain.add(current);
            if (current instanceof ScanOperator) {
                return chain;
            }
            if (!(current instanceof FilterOperator || current instanceof ProjectOperator)) {
                throw new PravahaException(
                        CodegenErrors.UNSUPPORTED,
                        current.label() + " ends a fused stage and is not generable in this wave. "
                                + "The interpreted path runs it (design 12.4).");
            }
            current = current.inputs().get(0);
        }
    }

    private static List<Integer> identity(int size) {
        List<Integer> ordinals = new ArrayList<>(size);
        for (int i = 0; i < size; i++) {
            ordinals.add(i);
        }
        return ordinals;
    }
}
