/*
 * Project Pravaha -- Ask once. Answer always.
 *
 * Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>.
 * All rights reserved.
 *
 * PROPRIETARY AND CONFIDENTIAL.
 *
 * This file is the confidential and proprietary property of Ashutosh Sinha.
 * Unauthorised copying, use, modification, distribution or disclosure of this
 * file, via any medium, is strictly prohibited except with the express prior
 * written permission of the copyright holder.
 *
 * See the LICENSE file in the root of this repository for the full terms.
 */
package com.ash.messaging.pravaha.pgwire;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;

import com.ash.messaging.pravaha.api.PravahaException;
import com.ash.messaging.pravaha.api.data.DecimalType;
import com.ash.messaging.pravaha.api.data.Field;
import com.ash.messaging.pravaha.api.data.StreamSchema;
import com.ash.messaging.pravaha.api.data.Types;
import com.ash.messaging.pravaha.security.Principal;
import com.ash.messaging.pravaha.security.SecurityPolicy;
import com.ash.messaging.pravaha.security.ViewNames;
import com.ash.messaging.pravaha.serving.ServedView;
import com.ash.messaging.pravaha.serving.ViewCatalog;
import com.ash.messaging.pravaha.serving.ViewQuery;

/**
 * A minimal, read-only {@code pg_catalog}, enough for {@code psql}'s {@code \d}, {@code \dt} and
 * {@code \d <view>} and for a JDBC or ADBC driver's table and column enumeration.
 *
 * <h2>Why this exists</h2>
 *
 * <p>{@code psql}'s backslash commands are not client-side conveniences -- they are SQL, sent to the
 * server exactly like anything typed at the prompt, against {@code pg_catalog.pg_class}, {@code
 * pg_namespace} and {@code pg_attribute}. Neither table exists in Pravaha's engine, so before this
 * class every one of those queries reached {@code ViewQuery}, which handed it to Calcite, which
 * refused it with a parse error naming syntax ({@code OPERATOR(pg_catalog.~)}, {@code ::regclass})
 * this engine's SQL dialect was never meant to understand. The gateway answered ordinary {@code
 * SELECT} correctly and failed every tool that wanted to show a table list first -- which is nearly
 * all of them.
 *
 * <h2>Why this is a recognizer, not a second SQL engine</h2>
 *
 * <p>The query text real clients send is not arbitrary: it is generated by {@code psql} and by
 * driver code, from a small, fixed set of templates that vary with the {@code server_version} this
 * gateway announces (see {@code PravahaPgWireServer.SERVER_VERSION}) and with the specific
 * introspection a client is doing. This class does not parse or evaluate general SQL against a
 * virtual {@code pg_catalog} -- it recognises each of those templates by a distinguishing marker,
 * and for each one it understands, computes the answer directly from {@link ViewCatalog} and {@link
 * SecurityPolicy} rather than by simulating PostgreSQL's own functions and joins. A real {@code
 * pg_get_expr} or {@code pg_table_is_visible} is never evaluated; this server just knows, for its
 * own single-schema, no-default, no-index world, what the honest answer to each of those questions
 * always is.
 *
 * <p><strong>A query in this family that this class does not recognise is refused by name</strong>
 * ({@link PgWireErrors#UNSUPPORTED_CATALOG_QUERY}), not approximated. Guessing at an unfamiliar
 * catalog query and returning something plausible is how a client is told a fact about the database
 * that is not true; {@code psql} prints whatever comes back as though it were real.
 *
 * <h2>Where authorization lives</h2>
 *
 * <p>Not differently from anywhere else in this module. SX-5 is exactly this shape of defect: a
 * catalog listing is still a read, and a principal must not learn that a view exists -- by name, by
 * column, or by successfully resolving its oid -- when {@link SecurityPolicy#mayRead} would refuse
 * to tell them so on an ordinary {@code SELECT}. Every row this class can produce is filtered by the
 * same {@code mayRead} plus the same {@code derivedFrom} provenance check {@code ViewQuery} and
 * {@code FlightSqlMetadata} both use (SX-11): a view is visible only if the principal may read both
 * the name it is registered under and everything it is built from. A forbidden view is not shown
 * with an "access denied" marker -- it is left out, exactly as if it did not exist, which is the one
 * answer a denied caller and a nonexistent name must share.
 */
final class PgCatalogShim {

    private final ViewCatalog catalog;
    private final SecurityPolicy policy;
    private final PgOidRegistry oids;
    private final String serverVersion;
    private final PgInformationSchema informationSchema;

    PgCatalogShim(ViewCatalog catalog, SecurityPolicy policy, PgOidRegistry oids, String serverVersion) {
        this.catalog = Objects.requireNonNull(catalog, "catalog");
        this.policy = Objects.requireNonNull(policy, "policy");
        this.oids = Objects.requireNonNull(oids, "oids");
        this.serverVersion = Objects.requireNonNull(serverVersion, "serverVersion");
        this.informationSchema = new PgInformationSchema(catalog);
    }

    /**
     * Answers {@code sql}, if it is one of the catalog shapes this class recognises.
     *
     * @return empty if {@code sql} is not directed at {@code pg_catalog} at all -- an ordinary query
     *     over a view, which the caller should run through {@link ViewQuery} as before
     * @throws PravahaException {@link PgWireErrors#UNSUPPORTED_CATALOG_QUERY} if {@code sql} is
     *     plainly catalog introspection but not a shape this class has been taught to answer
     */
    Optional<ViewQuery.Result> tryAnswer(String sql, Principal principal) {
        Optional<ViewQuery.Result> scalar = tryScalarFunction(sql);
        if (scalar.isPresent()) {
            return scalar;
        }
        if (!looksLikeCatalogQuery(sql)) {
            return Optional.empty();
        }
        Optional<ViewQuery.Result> types = tryNpgsqlTypeLoading(sql);
        if (types.isPresent()) {
            return types;
        }
        Optional<ViewQuery.Result> standard = informationSchema.tryAnswer(sql, shownViews(principal));
        if (standard.isPresent()) {
            return standard;
        }
        Optional<ViewQuery.Result> listing = tryRelationListing(sql, principal);
        if (listing.isPresent()) {
            return listing;
        }
        Optional<ViewQuery.Result> jdbcTables = tryJdbcGetTables(sql, principal);
        if (jdbcTables.isPresent()) {
            return jdbcTables;
        }
        Optional<ViewQuery.Result> jdbcColumns = tryJdbcGetColumns(sql, principal);
        if (jdbcColumns.isPresent()) {
            return jdbcColumns;
        }
        Optional<ViewQuery.Result> resolve = tryResolveByName(sql, principal);
        if (resolve.isPresent()) {
            return resolve;
        }
        Optional<ViewQuery.Result> flags = tryRelationFlags(sql, principal);
        if (flags.isPresent()) {
            return flags;
        }
        Optional<ViewQuery.Result> columns = tryColumnList(sql, principal);
        if (columns.isPresent()) {
            return columns;
        }
        // FROM pg_catalog.pg_inherits: parent/child partitions and inheritance, neither of which a
        // Pravaha view has ever had one of. Always the true, empty answer -- not a shape refused for
        // being unrecognised, but one recognised and always answered the same way.
        if (containsIgnoreCase(sql, "pg_inherits")) {
            return Optional.of(new ViewQuery.Result(
                    StreamSchema.builder("pg_inherits")
                            .field("oid", Types.string())
                            .build(),
                    List.of()));
        }
        throw new PravahaException(
                PgWireErrors.UNSUPPORTED_CATALOG_QUERY,
                "this looks like a pg_catalog query this gateway does not recognise: " + preview(sql)
                        + ". PgCatalogShim answers the specific query shapes psql (at the server_version this "
                        + "gateway announces), a JDBC driver's own metadata calls, Npgsql's type loading and "
                        + "GetSchema, and Power BI's navigator send -- table and column listing, chiefly -- "
                        + "and refuses anything else by name rather than approximate a "
                        + "PostgreSQL function or join this server has never implemented.");
    }

    // ------------------------------------------------------------------------------------------
    // Bare scalar functions: version(), current_schema(), and the like.
    // ------------------------------------------------------------------------------------------

    private static final Pattern BARE_SELECT_LIST =
            Pattern.compile("^SELECT\\s+(.+?)\\s*$", Pattern.CASE_INSENSITIVE | Pattern.DOTALL);

    private Optional<ViewQuery.Result> tryScalarFunction(String sql) {
        Matcher match = BARE_SELECT_LIST.matcher(sql.strip());
        if (!match.matches()
                || match.group(1).contains(",")
                || match.group(1).toUpperCase(Locale.ROOT).contains("FROM")) {
            return Optional.empty();
        }
        String expr = match.group(1).strip();
        String value =
                switch (normalizeCall(expr)) {
                    case "VERSION()" -> "PostgreSQL " + serverVersion + " -- Pravaha's PostgreSQL wire gateway";
                    case "CURRENT_SCHEMA()", "CURRENT_SCHEMA" -> "public";
                    case "CURRENT_DATABASE()", "CURRENT_CATALOG" -> "pravaha";
                    case "PG_BACKEND_PID()" ->
                        String.valueOf(ProcessHandle.current().pid());
                    default -> null;
                };
        if (value == null) {
            return Optional.empty();
        }
        StreamSchema schema = StreamSchema.builder("scalar")
                .field(columnNameFor(expr), Types.string())
                .build();
        return Optional.of(new ViewQuery.Result(schema, java.util.Collections.singletonList(new Object[] {value})));
    }

    private static String normalizeCall(String expr) {
        return expr.toUpperCase(Locale.ROOT).replaceAll("\\s+", "").replaceAll(";$", "");
    }

    private static String columnNameFor(String expr) {
        int paren = expr.indexOf('(');
        String base = paren >= 0 ? expr.substring(0, paren) : expr;
        return base.toLowerCase(Locale.ROOT);
    }

    // ------------------------------------------------------------------------------------------
    // Npgsql's type loading: three statements, sent as one batch every time a connection opens.
    // ------------------------------------------------------------------------------------------

    /**
     * Npgsql 4.0's {@code PostgresDatabaseInfo.GenerateTypesQuery} -- the driver Power BI bundles --
     * sends these three on every connection open, with type loading on (the default, and not
     * something Power BI lets a user turn off), and fails the open if any is refused. Each is
     * recognised by the join only it makes:
     *
     * <ol>
     *   <li>"Load all supported types": {@code pg_proc.proname='array_recv'} over {@code pg_type AS
     *       a}. Answered with the ten base types this gateway puts on the wire ({@link PgTypes#oidOf}'s
     *       range), under their real PostgreSQL oids and names -- and nothing else: no arrays, ranges,
     *       enums or domains, because no column here is ever one. Npgsql binds its readers to these by
     *       name, and a type it is not told about is one it reads as unknown, which is correct for a
     *       type this server never sends.
     *   <li>"Load field definitions for (free-standing) composite types": none exist. Empty.
     *   <li>"Load enum fields": none exist. Empty.
     * </ol>
     *
     * <p>Npgsql reads all three as text ({@code AllResultTypesAreUnknown}), by column name.
     */
    private static final Pattern NPGSQL_TYPES_MARKER = Pattern.compile(
            "pg_proc\\.proname\\s*=\\s*'array_recv'.*FROM\\s+pg_type\\s+AS\\s+a\\b",
            Pattern.CASE_INSENSITIVE | Pattern.DOTALL);

    private static final Pattern NPGSQL_COMPOSITES_MARKER = Pattern.compile(
            "JOIN\\s+pg_attribute\\s+AS\\s+att\\s+ON\\s*\\(\\s*att\\.attrelid\\s*=\\s*typ\\.typrelid\\s*\\)",
            Pattern.CASE_INSENSITIVE);

    private static final Pattern NPGSQL_ENUMS_MARKER = Pattern.compile(
            "SELECT\\s+pg_type\\.oid\\s*,\\s*enumlabel\\s+FROM\\s+pg_enum\\b", Pattern.CASE_INSENSITIVE);

    /** (oid, typname) of every type this gateway can put on the wire, as PostgreSQL numbers them. */
    private static final Object[][] WIRE_TYPES = {
        {PgTypes.OID_BOOL, "bool"},
        {PgTypes.OID_INT8, "int8"},
        {PgTypes.OID_INT2, "int2"},
        {PgTypes.OID_INT4, "int4"},
        {PgTypes.OID_TEXT, "text"},
        {PgTypes.OID_FLOAT4, "float4"},
        {PgTypes.OID_FLOAT8, "float8"},
        {PgTypes.OID_DATE, "date"},
        {PgTypes.OID_TIMESTAMPTZ, "timestamptz"},
        {PgTypes.OID_NUMERIC, "numeric"},
    };

    private static Optional<ViewQuery.Result> tryNpgsqlTypeLoading(String sql) {
        if (NPGSQL_TYPES_MARKER.matcher(sql).find()) {
            StreamSchema schema = StreamSchema.builder("npgsql_types")
                    .field("nspname", Types.string())
                    .field("typname", Types.string())
                    .field("oid", Types.int32())
                    .field("typrelid", Types.int32())
                    .field("typbasetype", Types.int32())
                    .field("type", Types.string())
                    .field("elemoid", Types.int32())
                    .field("ord", Types.int32())
                    .build();
            List<Object[]> rows = new ArrayList<>();
            for (Object[] type : WIRE_TYPES) {
                // A base type ('b'): no relation, no base type, no element, sorted first (ord 0).
                rows.add(new Object[] {"pg_catalog", type[1], type[0], 0, 0, "b", 0, 0});
            }
            return Optional.of(new ViewQuery.Result(schema, rows));
        }
        if (NPGSQL_COMPOSITES_MARKER.matcher(sql).find()) {
            return Optional.of(new ViewQuery.Result(
                    StreamSchema.builder("npgsql_composite_fields")
                            .field("oid", Types.int32())
                            .field("attname", Types.string())
                            .field("atttypid", Types.int32())
                            .build(),
                    List.of()));
        }
        if (NPGSQL_ENUMS_MARKER.matcher(sql).find()) {
            return Optional.of(new ViewQuery.Result(
                    StreamSchema.builder("npgsql_enum_labels")
                            .field("oid", Types.int32())
                            .field("enumlabel", Types.string())
                            .build(),
                    List.of()));
        }
        return Optional.empty();
    }

    // ------------------------------------------------------------------------------------------
    // \d / \dt: list relations.
    // ------------------------------------------------------------------------------------------

    // pg_get_userbyid is the marker, not the bare "CASE c.relkind" that also appears -- with
    // different column names entirely -- inside pgjdbc's own getTables() query (see
    // tryJdbcGetTables). Two clients can both touch pg_class.relkind in a CASE expression while
    // wanting completely different result shapes; this class has to tell them apart before it
    // answers, or one gets the other's column names.
    private static final Pattern LISTING_MARKER =
            Pattern.compile("pg_get_userbyid\\s*\\(\\s*c\\.relowner\\s*\\)", Pattern.CASE_INSENSITIVE);

    private Optional<ViewQuery.Result> tryRelationListing(String sql, Principal principal) {
        if (!LISTING_MARKER.matcher(sql).find()) {
            return Optional.empty();
        }
        StreamSchema schema = StreamSchema.builder("pg_class_listing")
                .field("Schema", Types.string())
                .field("Name", Types.string())
                .field("Type", Types.string())
                .field("Owner", Types.string())
                .build();
        List<Object[]> rows = new ArrayList<>();
        for (String name : shownViews(principal).keySet()) {
            rows.add(new Object[] {"public", name, "table", owner()});
        }
        return Optional.of(new ViewQuery.Result(schema, rows));
    }

    // ------------------------------------------------------------------------------------------
    // JDBC's DatabaseMetaData.getTables() -- a different query for the same question.
    // ------------------------------------------------------------------------------------------

    /**
     * pgjdbc's own marker: it names every column {@code DatabaseMetaData.getTables()} is specified
     * to return, quoted exactly as the JDBC caller expects to find them, which is also what makes
     * getting this one right matter more than getting {@code \d} right -- this is the query behind
     * "DBeaver lists your tables".
     */
    private static final Pattern JDBC_GET_TABLES_MARKER = Pattern.compile(
            "AS\\s+\"TABLE_CAT\".*AS\\s+\"TABLE_SCHEM\".*AS\\s+\"TABLE_NAME\".*AS\\s+\"TABLE_TYPE\"",
            Pattern.CASE_INSENSITIVE | Pattern.DOTALL);

    private static final Pattern RELKIND_TABLE_WANTED =
            Pattern.compile("c\\.relkind\\s*=\\s*'r'", Pattern.CASE_INSENSITIVE);
    private static final Pattern RELKIND_FILTERED_AT_ALL =
            Pattern.compile("c\\.relkind\\s*=\\s*'", Pattern.CASE_INSENSITIVE);

    private Optional<ViewQuery.Result> tryJdbcGetTables(String sql, Principal principal) {
        if (!JDBC_GET_TABLES_MARKER.matcher(sql).find()) {
            return Optional.empty();
        }
        StreamSchema schema = StreamSchema.builder("jdbc_get_tables")
                .field("TABLE_CAT", Types.string())
                .field("TABLE_SCHEM", Types.string())
                .field("TABLE_NAME", Types.string())
                .field("TABLE_TYPE", Types.string())
                .field("REMARKS", Types.string())
                .field("TYPE_CAT", Types.string())
                .field("TYPE_SCHEM", Types.string())
                .field("TYPE_NAME", Types.string())
                .field("SELF_REFERENCING_COL_NAME", Types.string())
                .field("REF_GENERATION", Types.string())
                .build();
        List<Object[]> rows = new ArrayList<>();
        // Pravaha has one kind of relation: an ordinary table, PostgreSQL relkind 'r'. A caller that
        // asked only for some other kind (a view filter that names 'v', 'i', and so on but not 'r')
        // gets none of these rows, which is correct rather than a gap -- there is nothing of that
        // kind to report. A caller that filtered on nothing at all (every default kind, the common
        // case) sees them, same as one that explicitly asked for 'r'.
        boolean wantsOrdinaryTables = RELKIND_TABLE_WANTED.matcher(sql).find()
                || !RELKIND_FILTERED_AT_ALL.matcher(sql).find();
        if (wantsOrdinaryTables) {
            for (String name : shownViews(principal).keySet()) {
                rows.add(new Object[] {"pravaha", "public", name, "TABLE", null, "", "", "", "", ""});
            }
        }
        return Optional.of(new ViewQuery.Result(schema, rows));
    }

    // ------------------------------------------------------------------------------------------
    // JDBC's DatabaseMetaData.getColumns().
    // ------------------------------------------------------------------------------------------

    /**
     * pgjdbc does not alias {@code pg_attribute} straight into JDBC's public column names the way it
     * does for {@code getTables()}: it runs this raw, un-aliased query -- {@code atttypid}, {@code
     * attnotnull}, {@code attnum} by {@code row_number()}, and the rest -- and builds the {@code
     * DATA_TYPE}/{@code TYPE_NAME}/{@code NULLABLE} columns {@code getColumns()} actually returns
     * from these, in Java, on the driver side. {@code row_number() OVER (PARTITION BY a.attrelid
     * ORDER BY a.attnum)} is the marker: nothing else this gateway answers computes attnum that way.
     */
    private static final Pattern JDBC_GET_COLUMNS_MARKER = Pattern.compile(
            "row_number\\s*\\(\\s*\\)\\s*OVER\\s*\\(\\s*PARTITION\\s+BY\\s+a\\.attrelid", Pattern.CASE_INSENSITIVE);

    private static final Pattern JDBC_TABLE_NAME_LIKE =
            Pattern.compile("c\\.relname\\s+LIKE\\s*\\(?\\s*'((?:[^']|'')*)'", Pattern.CASE_INSENSITIVE);
    private static final Pattern JDBC_COLUMN_NAME_LIKE =
            Pattern.compile("a\\.attname\\s+LIKE\\s*\\(?\\s*'((?:[^']|'')*)'", Pattern.CASE_INSENSITIVE);

    private Optional<ViewQuery.Result> tryJdbcGetColumns(String sql, Principal principal) {
        if (!JDBC_GET_COLUMNS_MARKER.matcher(sql).find()) {
            return Optional.empty();
        }
        // The exact projection pgjdbc's PgDatabaseMetaData#getColumns selects, positionally: it reads
        // this ResultSet by ordinal on the driver side, not by these names, but the names document
        // what each ordinal is answering.
        StreamSchema schema = StreamSchema.builder("jdbc_get_columns_raw")
                .field("current_database", Types.string())
                .field("nspname", Types.string())
                .field("relname", Types.string())
                .field("attname", Types.string())
                .field("atttypid", Types.int32())
                .field("attnotnull", Types.bool())
                .field("atttypmod", Types.int32())
                .field("attlen", Types.int32())
                .field("typtypmod", Types.int32())
                .field("attnum", Types.int32())
                .field("attidentity", Types.string())
                .field("attgenerated", Types.string())
                .field("adsrc", Types.string())
                .field("description", Types.string())
                .field("typbasetype", Types.int32())
                .field("typtype", Types.string())
                .build();
        String tableNamePattern = likeLiteral(JDBC_TABLE_NAME_LIKE, sql);
        String columnNamePattern = likeLiteral(JDBC_COLUMN_NAME_LIKE, sql);
        List<Object[]> rows = new ArrayList<>();
        for (Map.Entry<String, ServedView> shown : shownViews(principal).entrySet()) {
            String name = shown.getKey();
            if (tableNamePattern != null && !likeMatches(tableNamePattern, name)) {
                continue;
            }
            ServedView view = shown.getValue();
            if (view == null) {
                continue;
            }
            int ordinal = 1;
            for (Field field : view.schema().fields()) {
                if (columnNamePattern != null && !likeMatches(columnNamePattern, field.name())) {
                    ordinal++;
                    continue;
                }
                short fixedWidth = PgTypes.typeSizeOf(field.type().typeName());
                rows.add(new Object[] {
                    "pravaha",
                    "public",
                    name,
                    field.name(),
                    catalogTypeOid(field),
                    !field.type().nullable(),
                    PgTypes.typeModifierOf(field),
                    (int) fixedWidth, // already -1 for a variable-width type, matching real attlen
                    PgTypes.NO_TYPE_MODIFIER,
                    ordinal,
                    null, // attidentity: no column is GENERATED ... AS IDENTITY
                    null, // attgenerated: no column is a generated column
                    null, // adsrc: no column has a default
                    null, // description: no column comment
                    0, // typbasetype: not a domain over another type
                    "b" // typtype: a base type, always, in this engine's type system
                });
                ordinal++;
            }
        }
        return Optional.of(new ViewQuery.Result(schema, rows));
    }

    /** The literal inside a {@code column LIKE '...'} (optionally parenthesised) clause, or null. */
    private static String likeLiteral(Pattern likeClause, String sql) {
        Matcher match = likeClause.matcher(sql);
        return match.find() ? match.group(1).replace("''", "'") : null;
    }

    /** A SQL {@code LIKE} pattern (only {@code %} and {@code _} are special) against one name. */
    private static boolean likeMatches(String likePattern, String value) {
        StringBuilder regex = new StringBuilder(likePattern.length() + 8);
        for (int i = 0; i < likePattern.length(); i++) {
            char c = likePattern.charAt(i);
            if (c == '%') {
                regex.append(".*");
            } else if (c == '_') {
                regex.append('.');
            } else {
                regex.append(Pattern.quote(String.valueOf(c)));
            }
        }
        return value.matches(regex.toString());
    }

    // ------------------------------------------------------------------------------------------
    // \d <table>, query 1: resolve a name (or a pattern) to an oid.
    // ------------------------------------------------------------------------------------------

    private static final Pattern RESOLVE_MARKER = Pattern.compile(
            "SELECT\\s+c\\.oid\\s*,\\s*n\\.nspname\\s*,\\s*c\\.relname", Pattern.CASE_INSENSITIVE | Pattern.DOTALL);

    private static final Pattern RESOLVE_PATTERN_CLAUSE = Pattern.compile(
            "c\\.relname\\s*(?:OPERATOR\\s*\\([^)]*\\)|!?~)\\s*'((?:[^']|'')*)'", Pattern.CASE_INSENSITIVE);

    private Optional<ViewQuery.Result> tryResolveByName(String sql, Principal principal) {
        if (!RESOLVE_MARKER.matcher(sql).find()) {
            return Optional.empty();
        }
        StreamSchema schema = StreamSchema.builder("pg_class_resolve")
                .field("oid", Types.string())
                .field("nspname", Types.string())
                .field("relname", Types.string())
                .build();
        Matcher patternMatch = RESOLVE_PATTERN_CLAUSE.matcher(sql);
        boolean negate = false;
        Pattern namePattern = null;
        if (patternMatch.find()) {
            String literal = patternMatch.group(1).replace("''", "'");
            negate = patternMatch.group().trim().startsWith("!");
            namePattern = compileOrNull(literal);
        }
        List<Object[]> rows = new ArrayList<>();
        for (String engine : visibleViews(principal)) {
            // The oid is the engine name's (ADR-060): two tenants' orders are two relations.
            String name = ViewNames.shown(principal, engine);
            boolean matches = namePattern == null || namePattern.matcher(name).find();
            if (matches == !negate) {
                rows.add(new Object[] {String.valueOf(oids.oidOf(engine)), "public", name});
            }
        }
        rows.sort(Comparator.comparing(row -> (String) row[2]));
        return Optional.of(new ViewQuery.Result(schema, rows));
    }

    /** A best-effort ERE-to-Java {@link Pattern}, or {@code null} if it will not compile. */
    private static Pattern compileOrNull(String posixEre) {
        try {
            return Pattern.compile(posixEre);
        } catch (PatternSyntaxException unparseable) {
            return null;
        }
    }

    // ------------------------------------------------------------------------------------------
    // \d <table>, query 2: the relation's own flags (indexes, rules, triggers, checks -- all false).
    // ------------------------------------------------------------------------------------------

    private static final Pattern FLAGS_MARKER = Pattern.compile("c\\.relchecks\\b", Pattern.CASE_INSENSITIVE);
    private static final Pattern OID_LITERAL = Pattern.compile("c\\.oid\\s*=\\s*'?(\\d+)'?", Pattern.CASE_INSENSITIVE);

    private Optional<ViewQuery.Result> tryRelationFlags(String sql, Principal principal) {
        if (!FLAGS_MARKER.matcher(sql).find()) {
            return Optional.empty();
        }
        StreamSchema schema = StreamSchema.builder("pg_class_flags")
                .field("relchecks", Types.string())
                .field("relkind", Types.string())
                .field("relhasindex", Types.string())
                .field("relhasrules", Types.string())
                .field("relhastriggers", Types.string())
                .field("relhasrowsecurity", Types.string())
                .field("relforcerowsecurity", Types.string())
                .field("relhasoids", Types.string())
                .field("relispartition", Types.string())
                .field("reltablespace_name", Types.string())
                .field("reltablespace", Types.string())
                .field("reloftype", Types.string())
                .field("relpersistence", Types.string())
                .field("relreplident", Types.string())
                .build();
        Optional<String> name = resolveVisibleOid(sql, OID_LITERAL, principal);
        List<Object[]> rows = name.isEmpty()
                ? List.of()
                // A view has no indexes, rules, triggers or check constraints -- so psql's \d never
                // asks a follow-up about any of them, which is what keeps this shim's query set
                // small: those follow-ups exist in real psql, and are simply never reached here.
                : java.util.Collections.singletonList(
                        new Object[] {"0", "r", "f", "f", "f", "f", "f", "f", "f", "", "0", "", "p", "d"});
        return Optional.of(new ViewQuery.Result(schema, rows));
    }

    // ------------------------------------------------------------------------------------------
    // \d <table>, query 3: the columns.
    // ------------------------------------------------------------------------------------------

    private static final Pattern ATTRIBUTE_MARKER =
            Pattern.compile("FROM\\s+pg_catalog\\.pg_attribute\\s+a\\b", Pattern.CASE_INSENSITIVE);
    private static final Pattern ATTRELID_LITERAL =
            Pattern.compile("a\\.attrelid\\s*=\\s*'?(\\d+)'?", Pattern.CASE_INSENSITIVE);

    private Optional<ViewQuery.Result> tryColumnList(String sql, Principal principal) {
        if (!ATTRIBUTE_MARKER.matcher(sql).find()) {
            return Optional.empty();
        }
        StreamSchema schema = StreamSchema.builder("pg_attribute_listing")
                .field("attname", Types.string())
                .field("format_type", Types.string())
                .field("default_expr", Types.string())
                .field("attnotnull", Types.string())
                .field("attcollation", Types.string())
                .field("attidentity", Types.string())
                .field("attgenerated", Types.string())
                .build();
        Optional<String> name = resolveVisibleOid(sql, ATTRELID_LITERAL, principal);
        List<Object[]> rows = new ArrayList<>();
        if (name.isPresent()) {
            ServedView view = catalog.find(name.get()).orElse(null);
            if (view != null) {
                for (Field field : view.schema().fields()) {
                    rows.add(new Object[] {
                        field.name(),
                        formatType(field),
                        null, // no column has a default: nothing in this engine defaults a value
                        field.type().nullable() ? "f" : "t",
                        null, // no column has a non-default collation
                        "", // attidentity: no column is GENERATED ... AS IDENTITY
                        "" // attgenerated: no column is a generated column
                    });
                }
            }
        }
        return Optional.of(new ViewQuery.Result(schema, rows));
    }

    /**
     * The oid literal in {@code sql}, resolved back to a view name this principal may actually read.
     *
     * <p>SX-5 lives here as much as in {@link #visibleViews}: a client that has seen an oid on one
     * connection -- or simply guessed one, they are small consecutive integers -- must not use it on
     * another to learn about a view a fresh {@code mayRead} would refuse. Not found and not
     * authorized come back identically: empty.
     */
    private Optional<String> resolveVisibleOid(String sql, Pattern oidLiteral, Principal principal) {
        Matcher match = oidLiteral.matcher(sql);
        if (!match.find()) {
            return Optional.empty();
        }
        int oid = Integer.parseInt(match.group(1));
        return oids.nameOf(oid)
                .filter(name -> ViewNames.visibleTo(principal, name)
                        && mayRead(principal, name)
                        && mayReadEverythingBehind(principal, name));
    }

    // ------------------------------------------------------------------------------------------
    // Shared: visibility (SX-5 / SX-11), type display, and recognition.
    // ------------------------------------------------------------------------------------------

    /**
     * The views this principal may see, in a stable order so two listings agree.
     *
     * <p>The same two-part rule {@code FlightSqlMetadata.visible} enforces on the Flight SQL side:
     * the name and the lineage both decide, because SX-11 was a principal denied "payroll" shown six
     * payroll-reading views anyway, because somebody else had chosen their names.
     */
    private List<String> visibleViews(Principal principal) {
        // ADR-060: by engine name, the caller's tenant's only -- every tenant's for an admin.
        List<String> names = new ArrayList<>(catalog.names());
        names.removeIf(name -> !ViewNames.visibleTo(principal, name)
                || !mayRead(principal, name)
                || !mayReadEverythingBehind(principal, name));
        names.sort(Comparator.comparing(name -> ViewNames.shown(principal, name)));
        return names;
    }

    /** {@link #visibleViews}, by the name each is shown to {@code principal} under, in that order. */
    private Map<String, ServedView> shownViews(Principal principal) {
        Map<String, ServedView> shown = new java.util.LinkedHashMap<>();
        for (String engine : visibleViews(principal)) {
            catalog.find(engine).ifPresent(view -> shown.put(ViewNames.shown(principal, engine), view));
        }
        return shown;
    }

    private boolean mayRead(Principal principal, String name) {
        return policy.mayRead(principal, name).allowed();
    }

    private boolean mayReadEverythingBehind(Principal principal, String name) {
        ServedView view = catalog.find(name).orElse(null);
        if (view == null) {
            return false;
        }
        for (String stream : view.derivedFrom()) {
            if (!stream.equals(name) && !mayRead(principal, stream)) {
                return false;
            }
        }
        return true;
    }

    /**
     * A PostgreSQL type name for {@code \d}'s "Type" column -- descriptive, not a wire promise.
     *
     * <p>Unlike {@link PgTypes#oidOf}, this never refuses. {@code \d} describing a {@code BYTES} or
     * {@code TIME} column and a client then failing to {@code SELECT} it are two different, both
     * honest, facts: the column is real and declarable, and reading its value over this gateway does
     * not work yet (see {@link PgTypes}'s own documentation). Hiding the column from {@code \d}
     * would be the same defect stated the other way round -- a client told there is nothing there.
     */
    private static String formatType(Field field) {
        return switch (field.type().typeName()) {
            case BOOLEAN -> "boolean";
            case INT8, INT16 -> "smallint";
            case INT32 -> "integer";
            case INT64 -> "bigint";
            case FLOAT32 -> "real";
            case FLOAT64 -> "double precision";
            case DECIMAL -> {
                DecimalType decimal = (DecimalType) field.type();
                yield "numeric(" + decimal.precision() + "," + decimal.scale() + ")";
            }
            case STRING -> "text";
            case DATE -> "date";
            case TIMESTAMP_LTZ -> "timestamp with time zone";
            case BYTES -> "bytea";
            case TIME -> "time without time zone";
            // Whatever Pravaha itself calls the type, rather than a fabricated PostgreSQL syntax for
            // a shape (ARRAY, MAP, ROW) PostgreSQL's own type system does not have.
            default -> field.type().sqlName();
        };
    }

    /**
     * {@code pg_type.oid} for {@link #tryJdbcGetColumns}: also descriptive, not a wire promise, and
     * for the same reason {@link #formatType} is. {@link PgTypes#oidOf} refuses {@code BYTES} and
     * {@code TIME} because {@code RowDescription} for an actual {@code SELECT} must not claim a wire
     * encoding this gateway cannot fill -- but that refusal is about the *value*, and there is no
     * value here: this only tells a JDBC caller what a column's declared type is, the same question
     * {@code \d} answers. Real PostgreSQL oids, so pgjdbc's own type cache resolves them to the right
     * {@code java.sql.Types} constant without this server pretending to be a catalog it is not.
     */
    private static int catalogTypeOid(Field field) {
        return switch (field.type().typeName()) {
            case BYTES -> 17; // bytea
            case TIME -> 1083; // time without time zone
            default -> PgTypes.oidOf(field);
        };
    }

    /** {@code pg_get_userbyid(c.relowner)}'s answer: this server has one owner, always. */
    private static String owner() {
        return "pravaha";
    }

    private static final List<String> DOMAIN_MARKERS = List.of(
            "pg_catalog",
            "pg_class",
            "pg_namespace",
            "pg_attribute",
            "pg_type",
            "pg_inherits",
            "pg_am",
            "pg_roles",
            "pg_tablespace",
            "pg_description",
            "pg_attrdef",
            "pg_collation",
            "pg_proc",
            "pg_enum",
            "pg_range",
            "information_schema.");

    private static boolean looksLikeCatalogQuery(String sql) {
        for (String marker : DOMAIN_MARKERS) {
            if (containsIgnoreCase(sql, marker)) {
                return true;
            }
        }
        return false;
    }

    private static boolean containsIgnoreCase(String haystack, String needle) {
        return haystack.toLowerCase(Locale.ROOT).contains(needle.toLowerCase(Locale.ROOT));
    }

    private static String preview(String sql) {
        String collapsed = sql.strip().replaceAll("\\s+", " ");
        return collapsed.length() > 200 ? collapsed.substring(0, 200) + "..." : collapsed;
    }
}
