"""The evaluation harness: a golden set, scored by meaning rather than by text (ADR-058 §4).

Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>. All rights reserved.
PROPRIETARY AND CONFIDENTIAL. See the LICENSE file for the full terms.

The golden set (``resources/golden-set.json``, generated by ``tools/build_examples.py``) has one
**reference** case per continuous query of every case study -- its description, its reference SQL
and key -- and **negative** cases that must be refused or must raise a question: an aggregate kept
forever with no window, a join between two streams with no time bound, a stream that does not
exist.

Each case is drafted through :meth:`Assistant.draft` against the engine the caller points at, with
the case's own worked example taken out of the prompt (it would be the answer). Then:

* a **reference** case passes when the engine accepts the draft, it reads the same streams as the
  reference, and it is the same computation -- by **plan** (the engine's physical plan for both,
  normalised, and the same key; the API gives no fingerprint for unregistered SQL), or, in
  ``run`` mode, by **fingerprint** (both registered, and the engine's fingerprints compared) or by
  **answer** (both views read after ``settle_s`` and their rows compared as multisets);
* a **negative** case passes when the draft is refused or asks a question -- an accepted draft is
  a model that answered a different question, and is scored as one.

Recorded for every case: the outcome, repair turns, tokens, latency and the model that answered.

``run`` mode registers into the engine -- each name under ``prefix`` -- and drops what it
registered afterwards. It needs a node started with the case studies' streams and sample data
(each study's ``conf/application.yaml``), never a production engine.
"""

from __future__ import annotations

import dataclasses
import functools
import json
import time
from importlib import resources
from typing import TYPE_CHECKING, Any, Callable, Iterable, Mapping, Optional, Sequence

from pravaha.assist.context import ContextBuilder, load_examples
from pravaha.assist.drafting import Draft, normalise_plan, relations
from pravaha.assist.errors import AssistConfigError, AssistError

if TYPE_CHECKING:
    from pravaha.assist.assistant import Assistant

DEFAULT_PREFIX = "assist_eval_"


@dataclasses.dataclass(frozen=True)
class GoldenCase:
    id: str
    #: ``reference`` or ``negative``.
    kind: str
    study: str
    description: str
    #: The relations the case is about (a negative's may not exist).
    streams: "tuple[str, ...]"
    #: What the engine must have for the case to run; it is skipped otherwise.
    requires: "tuple[str, ...]"
    #: What the engine must not have (the stream that does not exist).
    absent: "tuple[str, ...]"
    #: ``accepted`` for a reference; ``refused`` and/or ``questions`` for a negative.
    expect: "tuple[str, ...]"
    reference: Optional[Mapping[str, Any]] = None
    why: str = ""

    @classmethod
    def of(cls, document: Mapping[str, Any]) -> "GoldenCase":
        return cls(
            id=str(document["id"]),
            kind=str(document.get("kind", "reference")),
            study=str(document.get("study", "")),
            description=str(document.get("description", "")),
            streams=tuple(str(s) for s in document.get("streams") or []),
            requires=tuple(str(s) for s in document.get("requires") or []),
            absent=tuple(str(s) for s in document.get("absent") or []),
            expect=tuple(str(s) for s in document.get("expect") or []),
            reference=dict(document["reference"]) if document.get("reference") else None,
            why=str(document.get("why", "")),
        )


@functools.lru_cache(maxsize=1)
def _golden_document() -> "Mapping[str, Any]":
    node = resources.files("pravaha.assist").joinpath("resources").joinpath("golden-set.json")
    return dict(json.loads(node.read_text(encoding="utf-8")))


def load_golden_set() -> "list[GoldenCase]":
    """The packaged golden set: reference cases in id order, then the negative cases."""
    return [GoldenCase.of(c) for c in _golden_document().get("cases", [])]


@dataclasses.dataclass(frozen=True)
class CaseResult:
    id: str
    kind: str
    expected: "tuple[str, ...]"
    #: ``accepted``, ``refused``, ``questions``, ``error`` or ``skipped``.
    outcome: str
    #: ``None`` when skipped.
    passed: Optional[bool]
    #: How the draft was shown equal to the reference: ``fingerprint``, ``plan``, ``answer``.
    equal: Optional[str] = None
    inputs_match: Optional[bool] = None
    keys_match: Optional[bool] = None
    repairs: int = 0
    tokens: int = 0
    latency_ms: float = 0.0
    model: Optional[str] = None
    reason: str = ""
    sql: str = ""
    draft: Optional[Mapping[str, Any]] = None

    def to_dict(self, *, full: bool = False) -> dict[str, Any]:
        body: dict[str, Any] = {
            "id": self.id,
            "kind": self.kind,
            "expected": list(self.expected),
            "outcome": self.outcome,
            "passed": self.passed,
            "equal": self.equal,
            "inputsMatch": self.inputs_match,
            "keysMatch": self.keys_match,
            "repairs": self.repairs,
            "tokens": self.tokens,
            "latencyMs": self.latency_ms,
            "model": self.model,
            "reason": self.reason,
            "sql": self.sql,
        }
        if full and self.draft is not None:
            body["draft"] = dict(self.draft)
        return body


@dataclasses.dataclass(frozen=True)
class EvalReport:
    results: "tuple[CaseResult, ...]"
    profile: Optional[str]
    model: Optional[str]
    run: bool
    elapsed_ms: float

    def summary(self) -> dict[str, Any]:
        scored = [r for r in self.results if r.passed is not None]
        references = [r for r in scored if r.kind == "reference"]
        negatives = [r for r in scored if r.kind == "negative"]
        return {
            "cases": len(self.results),
            "scored": len(scored),
            "skipped": sum(1 for r in self.results if r.passed is None),
            "passed": sum(1 for r in scored if r.passed),
            "failed": sum(1 for r in scored if not r.passed),
            "errors": sum(1 for r in scored if r.outcome == "error"),
            "referencesAccepted": sum(1 for r in references if r.outcome == "accepted"),
            "referencesEqual": sum(1 for r in references if r.equal),
            "references": len(references),
            "negativesCaught": sum(1 for r in negatives if r.passed),
            "negatives": len(negatives),
            "questionsAsked": sum(1 for r in scored if r.outcome == "questions"),
            "repairs": sum(r.repairs for r in scored),
            "tokens": sum(r.tokens for r in scored),
            "latencyMs": round(sum(r.latency_ms for r in scored), 1),
            "models": sorted({r.model for r in scored if r.model}),
        }

    @property
    def all_passed(self) -> bool:
        return all(r.passed for r in self.results if r.passed is not None)

    def to_dict(self, *, full: bool = False) -> dict[str, Any]:
        return {
            "task": "assist-eval",
            "profile": self.profile,
            "model": self.model,
            "run": self.run,
            "elapsedMs": self.elapsed_ms,
            "summary": self.summary(),
            "results": [r.to_dict(full=full) for r in self.results],
        }


def _rows(result: Any) -> "list[tuple[Any, ...]]":
    """A view read as a sorted multiset of row tuples, in its column order."""
    rows = result.to_list() if hasattr(result, "to_list") else list(result)
    tuples = [tuple(row.values()) if isinstance(row, Mapping) else tuple(row) for row in rows]
    return sorted(tuples, key=repr)


class Evaluator:
    """Runs golden cases through an :class:`Assistant` and scores them.

    ``client`` (a :class:`pravaha.client.Client`) is needed only for ``run=True``, which
    registers each accepted draft and its reference under ``prefix``, compares the engine's
    fingerprints and, when they differ, the rows of both views after ``settle_s``, and drops both.
    """

    def __init__(
        self,
        assistant: "Assistant",
        *,
        profile: Optional[str] = None,
        model: Optional[str] = None,
        run: bool = False,
        client: Any = None,
        prefix: str = DEFAULT_PREFIX,
        settle_s: float = 5.0,
        sleep: Callable[[float], None] = time.sleep,
        progress: Optional[Callable[[CaseResult], None]] = None,
    ) -> None:
        if assistant.api is None:
            raise AssistConfigError("the evaluation needs the engine: construct the Assistant "
                                    "with an EngineApi")
        if run and client is None:
            raise AssistConfigError("--run registers into the engine and needs a Flight client "
                                    "(--url)")
        if not prefix or not prefix.replace("_", "a").isalnum() or prefix[0].isdigit():
            raise ValueError(f"prefix {prefix!r} must be letters, digits and underscores, and "
                             f"not start with a digit")
        self.assistant = assistant
        self.api = assistant.api
        self.profile = profile
        self.model = model
        self.run_mode = run
        self.client = client
        self.prefix = prefix
        self.settle_s = settle_s
        self.sleep = sleep
        self.progress = progress
        self._plans: dict[str, str] = {}

    # ------------------------------------------------------------------ one case

    def _skip(self, case: GoldenCase, readable: "set[str]") -> Optional[str]:
        missing = [s for s in case.requires if s.lower() not in readable]
        if missing:
            return (f"skipped: this engine has no {', '.join(missing)} you may read (start a node "
                    f"with {case.study}'s conf/application.yaml)")
        present = [s for s in case.absent if s.lower() in readable]
        if present:
            return f"skipped: this engine has {', '.join(present)}, which the case needs absent"
        return None

    def _reference_plan(self, case: GoldenCase) -> str:
        assert case.reference is not None and self.api is not None
        if case.id not in self._plans:
            self._plans[case.id] = normalise_plan(
                str(self.api.explain(str(case.reference["sql"]), "physical").get("plan") or ""))
        return self._plans[case.id]

    def _draft(self, case: GoldenCase) -> Draft:
        assert self.api is not None
        examples = [e for e in load_examples() if e.id != case.id]
        context = self.assistant.context_builder(examples).build(case.description)
        return self.assistant.draft(case.description, profile=self.profile, model=self.model,
                                    context=context)

    def score(self, case: GoldenCase, draft: Draft) -> CaseResult:
        """What ``draft`` earns for ``case`` (without ``run`` mode's registration)."""
        common: dict[str, Any] = {
            "id": case.id, "kind": case.kind, "expected": case.expect, "outcome": draft.status,
            "repairs": draft.repairs, "tokens": draft.tokens, "latency_ms": draft.latency_ms,
            "model": draft.answered_by.get("modelId"), "sql": draft.sql,
            "draft": draft.to_dict(),
        }
        if case.kind == "negative":
            if draft.status in case.expect:
                reason = ("refused: " + draft.verdict.words() if draft.status == "refused"
                          else "asked: " + " / ".join(draft.questions))
                return CaseResult(passed=True, reason=reason, **common)
            return CaseResult(passed=False, reason=(
                f"accepted a question that must be refused or asked about -- the draft reads "
                f"{', '.join(draft.inputs) or 'nothing'} and answers a different question "
                f"({case.why})"), **common)
        assert case.reference is not None
        if draft.status == "questions":
            return CaseResult(passed=False, reason="asked instead of drafting: "
                              + " / ".join(draft.questions), **common)
        if draft.status != "accepted":
            return CaseResult(passed=False, reason=draft.verdict.words(), **common)
        wanted = {s.lower() for s in relations(str(case.reference["sql"]))}
        inputs_match = {s.lower() for s in draft.inputs} == wanted
        reference_keys = [str(k).lower() for k in case.reference.get("keys") or []]
        keys_match = sorted(k.lower() for k in draft.keys) == sorted(reference_keys)
        if not inputs_match:
            return CaseResult(passed=False, inputs_match=False, keys_match=keys_match,
                              reason=f"reads {', '.join(draft.inputs)}; the reference reads "
                                     f"{', '.join(sorted(wanted))}", **common)
        same_plan = normalise_plan(draft.plan) == self._reference_plan(case)
        if same_plan and keys_match:
            return CaseResult(passed=True, equal="plan", inputs_match=True, keys_match=True,
                              reason="the engine's plan and the key equal the reference's",
                              **common)
        why = ("the plan differs from the reference's" if not same_plan
               else "the plan is the reference's but the key differs")
        return CaseResult(passed=False, inputs_match=True, keys_match=keys_match,
                          reason=why + (" (not compared by answer: --run does that)"
                                        if not self.run_mode else ""), **common)

    def _run(self, case: GoldenCase, draft: Draft, scored: CaseResult) -> CaseResult:
        """Registers the draft and the reference, compares fingerprints, then rows; drops both."""
        assert case.reference is not None and self.api is not None
        base = str(case.reference.get("name") or case.id.split("/")[-1])
        reference_name = f"{self.prefix}ref_{base}"
        draft_name = f"{self.prefix}draft_{base}"
        registered: list[str] = []
        try:
            fields = self.api.validate(str(case.reference["sql"])).get("outputFields") or []
            columns = [str(f.get("name")) for f in fields]
            ordinals = [columns.index(k) for k in case.reference.get("keys") or [] if k in columns]
            options = case.reference.get("options") or {}
            theirs = self.client.register(reference_name, str(case.reference["sql"]), ordinals,
                                          sink=None, retention=options.get("retention"))
            registered.append(reference_name)
            ours = self.client.register(draft_name, draft.sql, draft.key_ordinals(), sink=None,
                                        retention=draft.options.get("retention"))
            registered.append(draft_name)
            if theirs.fingerprint and theirs.fingerprint == ours.fingerprint:
                return dataclasses.replace(scored, passed=True, equal="fingerprint",
                                           reason="the engine's fingerprints are equal")
            self.sleep(self.settle_s)
            expected = _rows(self.client.query(f"SELECT * FROM {reference_name}"))
            answered = _rows(self.client.query(f"SELECT * FROM {draft_name}"))
            if not expected and not answered:
                return dataclasses.replace(scored, reason=scored.reason + "; both views were empty "
                                           f"after {self.settle_s:g} s: is sample data flowing?")
            if expected == answered:
                return dataclasses.replace(scored, passed=True, equal="answer",
                                           reason=f"the same {len(expected)} rows as the "
                                                  f"reference on this engine's data")
            return dataclasses.replace(scored, passed=False, reason=(
                f"a different answer: {len(answered)} rows against the reference's "
                f"{len(expected)}"))
        finally:
            for name in reversed(registered):
                try:
                    self.client.drop(name)
                except Exception:  # noqa: BLE001 - best effort; the report says what was left
                    pass

    def evaluate(self, case: GoldenCase, readable: "set[str]") -> CaseResult:
        skipped = self._skip(case, readable)
        if skipped:
            return CaseResult(case.id, case.kind, case.expect, "skipped", None, reason=skipped)
        try:
            draft = self._draft(case)
        except AssistConfigError:
            raise
        except AssistError as exc:
            return CaseResult(case.id, case.kind, case.expect, "error", False,
                              model=getattr(exc, "alias", None), reason=f"{exc.kind}: {exc}")
        scored = self.score(case, draft)
        if (self.run_mode and case.kind == "reference" and draft.accepted
                and scored.inputs_match and scored.equal is None):
            scored = self._run(case, draft, scored)
        return scored

    # ------------------------------------------------------------------ the set

    def run(
        self,
        cases: Optional[Sequence[GoldenCase]] = None,
        *,
        limit: Optional[int] = None,
        only: Iterable[str] = (),
    ) -> EvalReport:
        started = time.monotonic()
        chosen = list(cases if cases is not None else load_golden_set())
        wanted = [o for o in only if o]
        if wanted:
            chosen = [c for c in chosen if any(c.id == o or c.id.startswith(o.rstrip("/") + "/")
                                               or c.study == o for o in wanted)]
        if limit is not None:
            chosen = chosen[: max(0, limit)]
        assert self.api is not None
        streams, views, _sinks, _permissions, _notes = ContextBuilder(self.api).catalogue()
        readable = {str(s["name"]).lower() for s in streams} | \
            {str(v["name"]).lower() for v in views}
        results = []
        for case in chosen:
            result = self.evaluate(case, readable)
            results.append(result)
            if self.progress is not None:
                self.progress(result)
        return EvalReport(tuple(results), self.profile, self.model, self.run_mode,
                          round((time.monotonic() - started) * 1000.0, 1))


__all__ = [
    "CaseResult",
    "DEFAULT_PREFIX",
    "EvalReport",
    "Evaluator",
    "GoldenCase",
    "load_golden_set",
]
