"""The Python SDK's TLS configuration, against a real server.

Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>. All rights reserved.
PROPRIETARY AND CONFIDENTIAL. See the LICENSE file for the full terms.

A builder-only test proves nothing about whether a keyword argument reaches pyarrow's
transport correctly, or whether a certificate this SDK reads is one a real TLS handshake
actually accepts. So this starts a real, TLS-serving ``PravahaFlightServer`` --
``TestTlsFlightServerMain``, in this SDK's own test sources rather than in
``pravaha-flight`` -- with a fresh self-signed certificate generated by ``keytool``
per run, and connects the real Python client to it.

Skipped when the module has not been built, the same way ``test_client.py`` skips its
own cross-language fixture for the same reason.
"""

from __future__ import annotations

import os
import pathlib
import subprocess
import threading
import time

import pytest

pyarrow = pytest.importorskip("pyarrow", reason="the transport needs the 'flight' extra")

from pravaha import ClientOptions, TlsOptions, connect  # noqa: E402
from pravaha.client import ConnectError, QueryError  # noqa: E402

REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
SDK_FLIGHT_TARGET = REPO_ROOT / "sdk" / "pravaha-sdk-java-flight" / "target"
SDK_FLIGHT_TEST_CLASSES = SDK_FLIGHT_TARGET / "test-classes"


def _classpath() -> str:
    entries = [str(SDK_FLIGHT_TEST_CLASSES), str(SDK_FLIGHT_TARGET / "classes")]
    written = SDK_FLIGHT_TARGET / "test-classpath.txt"
    if written.exists():
        entries.append(written.read_text().strip())
    return os.pathsep.join(entries)


@pytest.fixture(scope="module")
def tls_server():
    if not SDK_FLIGHT_TEST_CLASSES.exists():
        pytest.skip(
            "sdk/pravaha-sdk-java-flight is not built; run "
            "./mvnw -pl sdk/pravaha-sdk-java-flight -am test-compile"
        )
    java = os.environ.get("JAVA_HOME", "")
    java_bin = str(pathlib.Path(java) / "bin" / "java") if java else "java"

    process = subprocess.Popen(
        [
            java_bin,
            "--add-opens=java.base/java.nio=ALL-UNNAMED",
            "--add-opens=java.base/java.lang=ALL-UNNAMED",
            "-cp",
            _classpath(),
            "com.ash.messaging.pravaha.sdk.flight.TestTlsFlightServerMain",
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )

    found = {}

    def drain():
        while True:
            line = process.stdout.readline()
            if not line:
                return
            if line.startswith("PRAVAHA_FLIGHT_TLS_PORT="):
                found["port"] = int(line.strip().split("=", 1)[1])
            elif line.startswith("PRAVAHA_FLIGHT_TLS_CERT="):
                found["cert"] = line.strip().split("=", 1)[1]
            elif line.startswith("PRAVAHA_FLIGHT_TLS_KEYSTORE="):
                found["keystore"] = line.strip().split("=", 1)[1]
            elif line.startswith("PRAVAHA_FLIGHT_TLS_KEYSTORE_PASSWORD="):
                found["keystore_password"] = line.strip().split("=", 1)[1]

    reader = threading.Thread(target=drain, daemon=True)
    reader.start()

    expected = {"port", "cert", "keystore", "keystore_password"}
    deadline = time.time() + 90
    while time.time() < deadline and not expected.issubset(found):
        time.sleep(0.05)
    if "port" not in found:
        process.kill()
        pytest.skip("the TLS Pravaha server did not start; is sdk/pravaha-sdk-java-flight built?")

    yield {
        "port": found["port"],
        "cert": pathlib.Path(found["cert"]),
        "keystore": pathlib.Path(found.get("keystore", "")),
        "keystore_password": found.get("keystore_password", ""),
    }
    process.kill()
    process.wait(timeout=30)


def test_a_python_client_trusting_a_private_ca_can_read_rows(tls_server) -> None:
    options = ClientOptions.create(
        f"grpc+tls://localhost:{tls_server['port']}",
        tls=TlsOptions(ca_certificate=tls_server["cert"]),
    )
    with connect(options=options) as client:
        rows = {(row["user_id"], row["total"]) for row in client.query("SELECT user_id, total FROM user_volume")}
    assert rows == {("u1", 300), ("u2", 50)}


def test_a_python_client_trusting_a_pkcs12_truststore_can_also_read_rows(tls_server) -> None:
    pytest.importorskip("cryptography", reason="keystore support needs 'pravaha[tls-keystore]'")
    options = ClientOptions.create(
        f"grpc+tls://localhost:{tls_server['port']}",
        tls=TlsOptions(
            trust_store=tls_server["keystore"],
            trust_store_password=tls_server["keystore_password"],
            trust_store_type="PKCS12",
        ),
    )
    with connect(options=options) as client:
        assert len(client.query("SELECT user_id FROM user_volume").to_list()) == 2


def test_a_python_client_without_the_ca_cannot_connect(tls_server) -> None:
    # The negative case that makes the tests above mean something: this server's self-signed
    # certificate is not trusted by the system's default trust store, so connecting without
    # configuring the CA must fail rather than quietly succeed.
    with pytest.raises((ConnectError, QueryError)):
        with connect(f"grpc+tls://localhost:{tls_server['port']}") as client:
            client.query("SELECT user_id FROM user_volume").to_list()
