"""``pravaha completion bash|zsh|fish``: a shell completion script made from the parser itself.

Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>. All rights reserved.
PROPRIETARY AND CONFIDENTIAL. See the LICENSE file for the full terms.

The script is generated, at the moment it is asked for, by walking the argparse tree -- commands,
their verbs, every option, the choices of an option or a positional that has them -- so it cannot
fall behind the CLI: a command added to ``_app.py`` completes the next time the script is sourced.
A hidden option (``help=argparse.SUPPRESS``) is not offered. Context names are the one thing
asked for when completing -- ``pravaha context list --names`` -- after ``--context`` and after
``context use|show|set|remove``, so a context added a moment ago completes. zsh uses the bash script through
``bashcompinit``; fish gets its own ``complete`` lines.

Install::

    source <(pravaha completion bash)                     # this shell; add it to ~/.bashrc to keep
    pravaha completion bash > ~/.local/share/bash-completion/completions/pravaha
    source <(pravaha completion zsh)                      # in ~/.zshrc, after compinit
    pravaha completion fish > ~/.config/fish/completions/pravaha.fish
"""

from __future__ import annotations

import argparse
from typing import Any, Optional

from pravaha.cli._common import EXIT_OK, Context

SHELLS = ("bash", "zsh", "fish")
PROG = "pravaha"

def walk(parser: argparse.ArgumentParser,
         path: "tuple[str, ...]" = ()) -> "dict[tuple[str, ...], dict[str, Any]]":
    """Every command path under ``parser``, with what may follow it: ``{path: {"subs": [names],
    "opts": [flags], "values": {flag: [choices] or None}}}``."""
    node: "dict[str, Any]" = {"subs": [], "opts": [], "values": {}}
    out = {path: node}
    for action in parser._actions:  # argparse has no public way to walk its tree
        if isinstance(action, argparse._SubParsersAction):
            for name, sub in action.choices.items():
                node["subs"].append(name)
                out.update(walk(sub, path + (name,)))
            continue
        if action.help == argparse.SUPPRESS:
            continue
        if not action.option_strings:
            if action.choices:  # a positional with choices: `lanes rebalance status`
                node["subs"].extend(str(choice) for choice in action.choices)
            continue
        for flag in action.option_strings:
            node["opts"].append(flag)
            if action.nargs != 0:
                node["values"][flag] = [str(c) for c in action.choices] if action.choices else None
    return out


def _key(path: "tuple[str, ...]") -> str:
    return " ".join(path)


def bash(tree: "dict[tuple[str, ...], dict[str, Any]]") -> str:
    steps, subs, opts, values = [], [], [], []
    for path, node in tree.items():
        if path:
            steps.append(f'      "{_key(path[:-1])}|{path[-1]}") path="{_key(path)}" ;;')
        if node["subs"]:
            subs.append(f'    "{_key(path)}") subs="{" ".join(node["subs"])}" ;;')
        takes = " ".join(sorted(node["values"]))
        opts.append(f'    "{_key(path)}") opts="{" ".join(sorted(node["opts"]))}"; vals="{takes}" ;;')
        for flag, choices in node["values"].items():
            if choices:
                values.append(f'    "{_key(path)}|{flag}") choices="{" ".join(choices)}" ;;')
    nl = "\n"
    return f'''# bash completion for {PROG}: generated by `{PROG} completion bash` from the CLI's own parser.
#   source <({PROG} completion bash)     (add the line to ~/.bashrc to keep it), or save it as
#   ~/.local/share/bash-completion/completions/{PROG}
_pravaha_complete() {{
  local cur prev path="" i w subs="" opts="" vals="" choices=""
  cur="${{COMP_WORDS[COMP_CWORD]}}"; prev="${{COMP_WORDS[COMP_CWORD-1]}}"
  for ((i=1; i<COMP_CWORD; i++)); do   # the command path: each word naming a child of the last
    w="${{COMP_WORDS[i]}}"
    case "$path|$w" in
{nl.join(steps)}
    esac
  done
  case "$path" in
{nl.join(subs)}
  esac
  case "$path" in
{nl.join(opts)}
  esac
  case "$path|$prev" in
    *"|--context"|"context show|show"|"context use|use"|"context set|set"|"context remove|remove")
      choices="$({PROG} context list --names 2>/dev/null)" ;;
{nl.join(values)}
    *) choices="" ;;
  esac
  if [[ -n "$choices" ]]; then COMPREPLY=($(compgen -W "$choices" -- "$cur")); return; fi
  if [[ " $vals " == *" $prev "* ]]; then COMPREPLY=($(compgen -f -- "$cur")); return; fi
  if [[ "$cur" == -* ]]; then COMPREPLY=($(compgen -W "$opts" -- "$cur")); return; fi
  if [[ -n "$subs" ]]; then COMPREPLY=($(compgen -W "$subs" -- "$cur")); return; fi
  COMPREPLY=($(compgen -f -- "$cur"))
}}
complete -o filenames -F _pravaha_complete {PROG}
'''


def zsh(tree: "dict[tuple[str, ...], dict[str, Any]]") -> str:
    return (
        f"# zsh completion for {PROG}: generated by `{PROG} completion zsh`, the bash script\n"
        f"# through bashcompinit.\n#   source <({PROG} completion zsh)     (in ~/.zshrc, after compinit)\n"
        "autoload -U +X compinit && compinit\n"
        "autoload -U +X bashcompinit && bashcompinit\n" + bash(tree)
    )


def _fish_quote(text: str) -> str:
    return "'" + text.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _fish_option(flag: str, choices: Any, at: str) -> str:
    spec = f"-l {flag[2:]}" if flag.startswith("--") else f"-s {flag[1:]}"
    if choices is ...:  # a switch: takes no value
        return f"complete -c {PROG} {at}{spec}"
    if choices:
        return f"complete -c {PROG} {at}{spec} -x -a {_fish_quote(' '.join(choices))}"
    return f"complete -c {PROG} {at}{spec} -r -F"


def fish(tree: "dict[tuple[str, ...], dict[str, Any]]") -> str:
    steps = [f'            case {_fish_quote(_key(p[:-1]) + "|" + p[-1])}\n'
             f'                set path {_fish_quote(_key(p))}' for p in tree if p]
    # The connection options are on every command: said once, with no condition, not 120 times.
    everywhere = set.intersection(*(set(node["opts"]) for node in tree.values()))
    root = tree[()]
    lines = [_fish_option(flag, root["values"].get(flag, ...), "") for flag in sorted(everywhere)]
    for path, node in tree.items():
        at = "-n " + _fish_quote('__pravaha_at "' + _key(path) + '"') + " "
        if node["subs"]:
            lines.append(f"complete -c {PROG} {at}-a {_fish_quote(' '.join(node['subs']))}")
        for flag in sorted(set(node["opts"]) - everywhere):
            lines.append(_fish_option(flag, node["values"].get(flag, ...), at))
    nl = "\n"
    return f'''# fish completion for {PROG}: generated by `{PROG} completion fish` from the CLI's own parser.
#   {PROG} completion fish > ~/.config/fish/completions/{PROG}.fish
function __pravaha_path
    set -l path ''
    set -l words (commandline -opc)
    set -e words[1]
    for w in $words
        switch "$path|$w"
{nl.join(steps)}
        end
    end
    echo $path
end
function __pravaha_at
    set -l here (__pravaha_path)
    test "$here" = "$argv[1]"
end
complete -c {PROG} -f
{nl.join(lines)}
complete -c {PROG} -l context -x -a '({PROG} context list --names 2>/dev/null)'
complete -c {PROG} -n '__pravaha_at "context use"; or __pravaha_at "context show"; or __pravaha_at "context set"; or __pravaha_at "context remove"' -a '({PROG} context list --names 2>/dev/null)'
'''


def generate(shell: str, parser: argparse.ArgumentParser) -> str:
    tree = walk(parser)
    return {"bash": bash, "zsh": zsh, "fish": fish}[shell](tree)


def completion(ctx: Context, parser: Optional[argparse.ArgumentParser] = None) -> int:
    from pravaha.cli._app import build_parser

    ctx.out.out.write(generate(ctx.args.shell, parser or build_parser()))
    return EXIT_OK
